#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

Daemons.run(File.join(File.dirname(__FILE__), 'lenses', 'chronos', 'service.rb'), {
  :app_name => 'chronosd',
  :dir_mode => :normal,
  :dir => 'pids',
  :multiple => false,
  :backtrace => true,
  :log_output => true
})