# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{convex}
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sherr\303\263d Faulks"]
  s.date = %q{2010-10-05}
  s.description = %q{Convex is a semantic conversation extractor. It uses the OpenCalais service to understand documents and generate a flurry of information which is stored and manipulated in novel ways by Convex and its lenses.}
  s.email = %q{dev@styledon.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "chronosd",
     "config.ru",
     "convex-1.1.0.gem",
     "convex.gemspec",
     "convexd",
     "doc/Calais.graffle",
     "doc/Convex Sequence.graffle",
     "doc/Convex Slides.key",
     "doc/How it works.graffle/QuickLook/Preview.pdf",
     "doc/How it works.graffle/QuickLook/Thumbnail.tiff",
     "doc/How it works.graffle/data.plist",
     "doc/How it works.graffle/image10.png",
     "doc/How it works.graffle/image12.png",
     "doc/How it works.graffle/image14.gif",
     "doc/How it works.graffle/image15.gif",
     "doc/How it works.graffle/image17.ico",
     "doc/How it works.graffle/image18.ico",
     "doc/How it works.graffle/image20.ico",
     "doc/How it works.graffle/image21.ico",
     "doc/How it works.graffle/image22.ico",
     "doc/How it works.graffle/image23.ico",
     "doc/How it works.graffle/image24.ico",
     "doc/How it works.graffle/image25.ico",
     "doc/How it works.graffle/image26.ico",
     "doc/How it works.graffle/image27.ico",
     "doc/How it works.graffle/image28.ico",
     "doc/How it works.graffle/image29.ico",
     "doc/How it works.graffle/image30.ico",
     "doc/How it works.graffle/image33.png",
     "doc/How it works.graffle/image34.png",
     "doc/How it works.graffle/image9.png",
     "doc/How it works.pages",
     "doc/IMG_0090.jpg",
     "doc/IMG_0091.jpg",
     "doc/IMG_0093.JPG",
     "doc/code.google.com:p:pubsubhubbub:.webloc",
     "doc/github.com:igrigorik:PubSubHubbub.webloc",
     "doc/github.com:igrigorik:em-websocket.webloc",
     "doc/www.igvita.com:.webloc",
     "doc/www.websockets.org:about.html.webloc",
     "lenses/chronos/client.rb",
     "lenses/chronos/lens.rb",
     "lenses/chronos/service.rb",
     "lenses/eros/client.rb",
     "lenses/eros/lens.rb",
     "lenses/eros/user.rb",
     "lib/calais_service.rb",
     "lib/command.rb",
     "lib/convex.rb",
     "lib/convex_service.rb",
     "lib/datum.rb",
     "lib/datum_type.rb",
     "lib/em-websocket/em-websocket.rb",
     "lib/em-websocket/em-websocket/connection.rb",
     "lib/em-websocket/em-websocket/debugger.rb",
     "lib/em-websocket/em-websocket/handler.rb",
     "lib/em-websocket/em-websocket/handler75.rb",
     "lib/em-websocket/em-websocket/handler76.rb",
     "lib/em-websocket/em-websocket/handler_factory.rb",
     "lib/em-websocket/em-websocket/websocket.rb",
     "lib/engine.rb",
     "lib/extensions.rb",
     "lib/logging.rb",
     "lib/service_ports.rb",
     "psd/Convex.psd",
     "web/public/fonts/Quicksand License.txt",
     "web/public/fonts/Quicksand_Bold-webfont.eot",
     "web/public/fonts/Quicksand_Bold-webfont.ttf",
     "web/public/fonts/Quicksand_Bold_Oblique-webfont.eot",
     "web/public/fonts/Quicksand_Bold_Oblique-webfont.ttf",
     "web/public/fonts/Quicksand_Book-webfont.eot",
     "web/public/fonts/Quicksand_Book-webfont.ttf",
     "web/public/fonts/Quicksand_Book_Oblique-webfont.eot",
     "web/public/fonts/Quicksand_Book_Oblique-webfont.ttf",
     "web/public/fonts/Quicksand_Dash-webfont.eot",
     "web/public/fonts/Quicksand_Dash-webfont.ttf",
     "web/public/fonts/Quicksand_Light-webfont.eot",
     "web/public/fonts/Quicksand_Light-webfont.ttf",
     "web/public/fonts/Quicksand_Light_Oblique-webfont.eot",
     "web/public/fonts/Quicksand_Light_Oblique-webfont.ttf",
     "web/public/images/site/convex.png",
     "web/public/javascripts/application.js",
     "web/public/javascripts/mootools-1.2.5-core-yc.js",
     "web/public/stylesheets/application.css",
     "web/public/stylesheets/quicksand.css",
     "web/views/index.erubis",
     "web/web.rb"
  ]
  s.homepage = %q{http://github.com/StyledOn/convex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{CONVersation EXtractor}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

