# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{convex}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sherr\303\263d Faulks"]
  s.date = %q{2010-09-16}
  s.description = %q{Convex is a semantic conversation extractor. It uses the OpenCalais service to understand documents and generate a flurry of information which is stored and manipulated in novel ways by Convex and its lenses.}
  s.email = %q{dev@styledon.com}
  s.files = [
    ".gitignore",
     "VERSION",
     "chronosd",
     "convexd",
     "doc/Calais.graffle",
     "doc/Convex Sequence.graffle",
     "doc/Convex Slides.key",
     "doc/How it works.graffle/QuickLook/Preview.pdf",
     "doc/How it works.graffle/QuickLook/Thumbnail.tiff",
     "doc/How it works.graffle/data.plist",
     "doc/How it works.graffle/image10.png",
     "doc/How it works.graffle/image12.png",
     "doc/How it works.graffle/image14.gif",
     "doc/How it works.graffle/image15.gif",
     "doc/How it works.graffle/image17.ico",
     "doc/How it works.graffle/image18.ico",
     "doc/How it works.graffle/image20.ico",
     "doc/How it works.graffle/image21.ico",
     "doc/How it works.graffle/image22.ico",
     "doc/How it works.graffle/image23.ico",
     "doc/How it works.graffle/image24.ico",
     "doc/How it works.graffle/image25.ico",
     "doc/How it works.graffle/image26.ico",
     "doc/How it works.graffle/image27.ico",
     "doc/How it works.graffle/image28.ico",
     "doc/How it works.graffle/image29.ico",
     "doc/How it works.graffle/image30.ico",
     "doc/How it works.graffle/image33.png",
     "doc/How it works.graffle/image34.png",
     "doc/How it works.graffle/image9.png",
     "doc/How it works.pages",
     "doc/IMG_0090.jpg",
     "doc/IMG_0091.jpg",
     "doc/IMG_0093.JPG",
     "doc/code.google.com:p:pubsubhubbub:.webloc",
     "doc/github.com:igrigorik:PubSubHubbub.webloc",
     "doc/github.com:igrigorik:em-websocket.webloc",
     "doc/www.igvita.com:.webloc",
     "doc/www.websockets.org:about.html.webloc",
     "lenses/chronos/client.rb",
     "lenses/chronos/lens.rb",
     "lenses/chronos/service.rb",
     "lenses/eros/client.rb",
     "lenses/eros/lens.rb",
     "lib/calais_service.rb",
     "lib/convex.rb",
     "lib/convex_service.rb",
     "lib/datum.rb",
     "lib/datum_type.rb",
     "lib/em-websocket/em-websocket.rb",
     "lib/em-websocket/em-websocket/connection.rb",
     "lib/em-websocket/em-websocket/debugger.rb",
     "lib/em-websocket/em-websocket/handler.rb",
     "lib/em-websocket/em-websocket/handler75.rb",
     "lib/em-websocket/em-websocket/handler76.rb",
     "lib/em-websocket/em-websocket/handler_factory.rb",
     "lib/em-websocket/em-websocket/websocket.rb",
     "lib/engine.rb",
     "lib/extensions.rb",
     "lib/logging.rb",
     "lib/service_ports.rb",
     "redis/.gitignore",
     "redis/BETATESTING.txt",
     "redis/BUGS",
     "redis/COPYING",
     "redis/Changelog",
     "redis/Makefile",
     "redis/README",
     "redis/TODO",
     "redis/adlist.c",
     "redis/adlist.h",
     "redis/ae.c",
     "redis/ae.h",
     "redis/ae_epoll.c",
     "redis/ae_kqueue.c",
     "redis/ae_select.c",
     "redis/anet.c",
     "redis/anet.h",
     "redis/client-libraries/README",
     "redis/config.h",
     "redis/dict.c",
     "redis/dict.h",
     "redis/fmacros.h",
     "redis/linenoise.c",
     "redis/linenoise.h",
     "redis/lzf.h",
     "redis/lzfP.h",
     "redis/lzf_c.c",
     "redis/lzf_d.c",
     "redis/mkreleasehdr.sh",
     "redis/pqsort.c",
     "redis/pqsort.h",
     "redis/redis-benchmark.c",
     "redis/redis-check-aof.c",
     "redis/redis-check-dump.c",
     "redis/redis-cli.c",
     "redis/redis.c",
     "redis/redis.h",
     "redis/sds.c",
     "redis/sds.h",
     "redis/sha1.c",
     "redis/sha1.h",
     "redis/solarisfixes.h",
     "redis/start",
     "redis/staticsymbols.h",
     "redis/stop",
     "redis/tests/assets/default.conf",
     "redis/tests/integration/aof.tcl",
     "redis/tests/integration/replication.tcl",
     "redis/tests/support/redis.tcl",
     "redis/tests/support/server.tcl",
     "redis/tests/support/test.tcl",
     "redis/tests/support/tmpfile.tcl",
     "redis/tests/support/util.tcl",
     "redis/tests/test_helper.tcl",
     "redis/tests/unit/auth.tcl",
     "redis/tests/unit/basic.tcl",
     "redis/tests/unit/expire.tcl",
     "redis/tests/unit/other.tcl",
     "redis/tests/unit/protocol.tcl",
     "redis/tests/unit/sort.tcl",
     "redis/tests/unit/type/hash.tcl",
     "redis/tests/unit/type/list.tcl",
     "redis/tests/unit/type/set.tcl",
     "redis/tests/unit/type/zset.tcl",
     "redis/utils/build-static-symbols.tcl",
     "redis/utils/redis-copy.rb",
     "redis/utils/redis-sha1.rb",
     "redis/utils/redis_init_script",
     "redis/zipmap.c",
     "redis/zipmap.h",
     "redis/zmalloc.c",
     "redis/zmalloc.h"
  ]
  s.homepage = %q{http://github.com/StyledOn/convex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{CONVersation EXtractor}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

